### ISSUE TITLE
NoClassDefFoundError when test produces no error

### ISSUE THREAD

**Issue by rnveach** [TestingResearchIllinois/NonDex#98]
This is the issue specified in https://github.com/TestingResearchIllinois/NonDex/issues/97

When trying to work on the following PR: https://github.com/checkstyle/checkstyle/pull/3517
Nondex failed in our CI with a weird error: https://travis-ci.org/checkstyle/checkstyle/jobs/173511656#L2063-L2066
````
testProcessJavadocWithLinkTag(com.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheckTest)  Time elapsed: 0.018 sec  <<< ERROR!
java.lang.Error: Error was thrown while processing /home/travis/build/checkstyle/checkstyle/src/test/resources/com/puppycrawl/tools/checkstyle/checks/imports/InputUnusedImportWithValueTag.java
	at com.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheckTest.testProcessJavadocWithLinkTag(UnusedImportsCheckTest.java:111)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.puppycrawl.tools.checkstyle.utils.JavadocUtils
	at com.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheckTest.testProcessJavadocWithLinkTag(UnusedImportsCheckTest.java:111)
````
The error is weird, because we have another CI that [just runs the tests by themselves and they pass fine](https://travis-ci.org/checkstyle/checkstyle/jobs/173511652) and the class in question was not modified in the PR. We can not reproduce the error locally or on some new CI runs.
We have been using nondex for a while and our master branch is passing.

**Comment by alexgyori** [comment]
Form my investigation it seems that even just rerunning the same code on Travis doesn't cause the failure anymore. It's not only that I can't reproduce it on my local machine, but even on Travis if I try the same build it doesn't fail anymore, right?

**Comment by alexgyori** [comment]
I ran the same code on Travis, and it seems it doesn't fail. It's very weird as I cannot reproduce it: https://travis-ci.org/alexgyori/checkstyle/jobs/173704238#L4989

**Comment by rnveach** [comment]
> Basically, rerunning NonDex will not fail anymore. Is that correct?

That is true so far. We haven't seen the issue again.

When it did happen, re-running the job did produce the same result, so it might be something related to its specific build.
````
Build image provisioning date and time
Thu Feb  5 15:09:33 UTC 2015
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
Linux Version
3.13.0-29-generic
$ jdk_switcher use oraclejdk8
Switching to Oracle JDK8 (java-8-oracle), JAVA_HOME will be set to /usr/lib/jvm/java-8-oracle
cache.1
$ java -Xmx32m -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
$ javac -J-Xmx32m -version
javac 1.8.0_31
````

**Comment by rnveach** [comment]
We are having the same issue again in another PR.

PR: https://github.com/checkstyle/checkstyle/pull/3756
CI: https://travis-ci.org/checkstyle/checkstyle/jobs/195323615#L1807-L1808

Same class that is failing to instantiate, `JavadocUtils`. Again, no errors locally.

**Comment by rnveach** [comment]
We got the issue again.

PR: https://github.com/checkstyle/checkstyle/pull/4060
CI: https://travis-ci.org/checkstyle/checkstyle/jobs/212737548#L1190-L1193

Is there any word on finding what is causing this?
